### ISSUE TITLE
Incorrect link in Unit 3 slide deck #1 on misrepresentation 

### ISSUE THREAD

**Issue by UnitCircle** [tidyverse/datascience-box#144]
In the Data Science Ethics Unit: https://datasciencebox.org/02-ethics.html

In the  slide deck: https://datasciencebox.org/course-materials/_slides/u3-d01-misrepresentation/u3-d01-misrepresentation.html#11

On the slide entitled "Graph Detective"

This link: https://livefreeordichotomize.com/2020/05/17/graph-detective/

Needs to get updated to: https://livefreeordichotomize.com/posts/2020-05-17-graph-detective/

Worth updating - this is a great example to show students!

**Comment by dhodge180** [comment]
I'll try and fix this for you...
