### ISSUE TITLE
Cannot access the Space

### ISSUE THREAD

**Issue by kshantigreene** [tidyverse/datascience-box#145]
I used the link from Hello World to access the space and it says Unable to Join space.. it may be full. I am currently just using a free version. Will it work if I get a paid subscription?

Thanks,
Kshanti

**Comment by mine-cetinkaya-rundel** [comment]
@kshantigreene The space doesn't appear to be full. And you don't need a paid account to access it. Would you share a screenshot of what you're seeing?

**Comment by kshantigreene** [comment]
Thank you for your quick reply. Here are the screenshots. 
![68245539-A946-4266-BDC1-746267FAD9B4](https://github.com/rstudio-education/datascience-box/assets/96250228/4ee89152-84b8-46ab-94d6-5de968245d13)
![4E4584CA-EE5A-4B8D-8072-3BCA7778F911](https://github.com/rstudio-education/datascience-box/assets/96250228/78c71d38-ef33-411c-b017-ba7ecbb6b2f1)
