### ISSUE TITLE
dsbox package not available on CRAN

### ISSUE THREAD

**Issue by kshantigreene** [tidyverse/datascience-box#147]
Is there another name for the data package?

![image](https://github.com/tidyverse/datascience-box/assets/96250228/71da1514-a693-4d8e-a7c6-5a4993de6dff)

**Comment by mine-cetinkaya-rundel** [comment]
Yup, you can currently only install from GitHub. The following will also work now.

```r
install.packages("remotes")
remotes::install_github("tidyverse/dsbox")
```

**Comment by kshantigreene** [comment]
[@minebocek](https://twitter.com/minebocek) Do you by chance have solutions to the assignments? I am getting stumped with some of them.

**Comment by mine-cetinkaya-rundel** [comment]
Which assignments are you referring to @kshantigreene?

**Comment by kshantigreene** [comment]
It was HW 2, exercise 4. I was struggle to get it grouped and sorted. I
figured it out, but I’m not sure it was how you would have expected your
students to do it, based on what you covered so far.

subset <-edibnb %>%
  group_by(neighbourhood) %>%
  summarize(MED=median(price,na.rm=TRUE)) %>%
  slice_max(order_by = MED, n=5)
