### ISSUE TITLE
misrepresentation broken slide 

### ISSUE THREAD

**Issue by rkportal** [tidyverse/datascience-box#152]
In u3-d01-misrepresentation.Rmd, the slide "Graph detective" looks like that:
![image](https://github.com/tidyverse/datascience-box/assets/129891838/3f42c716-c6b8-4278-be73-a73a53f1786b)
seem to be a broken link:
https://livefreeordichotomize.com/2020/05/17/graph-detective/

this will probably work:
https://livefreeordichotomize.com/posts/2020-05-17-graph-detective/

thanks for the course

**Comment by dhodge180** [comment]
I'll try and fix this for you...

**Comment by mine-cetinkaya-rundel** [comment]
Closed in #153
